language: node_js
node_js:
  - '12'
sudo: true

services:
    - docker

before_install:
  - cp src/config/config.dev.json src/config/config.json

install:
  - docker-compose up -d

script:
  - npm i
  - ./travis.wait.sh
  - docker ps
  - npm run test-int