version: "3.0"

networks:
    default_test:

services:
  df2-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    expose:
      - "4201"
    ports:
     - "4201:4201"
    networks:
        - default_test
    depends_on:
      - mysql
      - minio
      - memcache
    volumes:
      - ./src:/app/src
    healthcheck:
        test: [ "CMD", "curl", "localhost:4201/ping/" ]
        timeout: 5s
        interval: 3s
        retries: 10
    #command: ["ls", "-al", "src"]
  mysql:
    image: mysql:8.0.33-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    expose: # exposes 3306 on the internal container network for the server
      - "3306"
    ports: # allows connection from integration tests, or an external mysql client.
      - "33061:3306"
    networks:
        - default_test
  minio:
    image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
    expose:
      - "9000"
    ports:
     - "9000:9000"
    networks:
        - default_test
    command: ["server", "/data"]
  memcache:
    image: memcached:1.6.20-alpine3.18
    expose: # exposes 3306 on the internal container network for the server
      - "11211"
    ports:
      - "11211:11211"
    networks:
        - default_test