version: '3'
services:
  df2-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
     - "4201:4201"
    depends_on:
      - mysql
      - minio
      - memcache
    volumes:
      - ./src:/app/src
    #command: ["ls", "-al", "src"]
  mysql:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    expose:
      - "3306"
    command:
     - "--default-authentication-plugin=mysql_native_password"
  minio:
    image: minio/minio
    ports:
     - "9000:9000"
    command: ["server", "/data"]
  memcache:
    image: memcached

