CREATE TABLE IF NOT EXISTS `Admin` (
`int` tinyint(1) NOT NULL DEFAULT '0',
`last_wiki_pull` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`int`)
) DEFAULT CHARSET=utf8;